name = input("Enter Student's Name : ")
classname = input("Enter Class : ")
exam = input("Enter Examination : ")
maths = input("Enter Maths Marks : ")
physics = input("Enter Physics Marks : ")
chem = input("Enter Chemistry Marks : ")
maths=int(maths)
physics=int(physics)
chem=int(chem)
total = maths+physics+chem
pec=total
print("***********-Marksheet-**************")
print("------------------------------------")
print("Student Name : "+(name))
print("Class        : "+(classname))
print("Examination  : "+(exam))
print("------------------------------------")
print("Mathematics           "(maths))
print("Physics               "(physics))
print("Chemistry             "(chem))
print("------------------------------------")
print("Total                 "+(total))
print("Percentage            "+(pec))